### ISSUE TITLE
Support for Inverter Zucchetti 3ph hyd 15000 zss

### ISSUE THREAD

**Issue by antcan66** [ptrbojko/openhab-lsw4inverter-binding#5]
Serial number 2106******
inverter 3ph hyd 15000 zss
Firmware on LS eth is ME_0D_270A_1.08

Channel online is on but everything else is null.
in the log file I have this:
[al.protocolv5.UnknownResponseHandler] - Unknown response, length 9: A5:17:00:10:45:03:00:AE:02:
i tried both things versions with the same result.

**Comment by ptrbojko** [comment]
Hi, could check what options do you have when accessing your inverter/logger through http://ip-of-logger/config_hide.html ?

**Comment by antcan66** [comment]
![Schermata del 2023-04-14 08-49-24](https://user-images.githubusercontent.com/130691838/231966751-ae215c75-55e2-4239-ba22-2df8e2afc6c6.png)


![Schermata del 2023-04-14 08-51-13](https://user-images.githubusercontent.com/130691838/231966538-2890fb68-d62d-4825-9b10-92d3c9f76f38.png)

**Comment by antcan66** [comment]
in "mode select" actually blank i have 2 option AP+STA or AP/STA
in "invertor brand select" actually blank i have no selection
regards antonio

**Comment by ptrbojko** [comment]
I have seen somewhere that when changing **Working mode** from _Data collection_ to _Transparent_ - logger will accept solarman v5 protocol on port 8899 (which is used by this binding). The binding may work then.

You may experiment with this option. Please, be aware, that this change may limit ability to report to solarman cloud app - I do not know the overall outcomes.

If there is more than _Transparent_ and _Data Collection_ options im **Working mode** - please share here.

**Comment by antcan66** [comment]
If i change working mode to Trasparent  the status remains permanently at unknown

**Comment by antcan66** [comment]
No. In working mode Just 2 options
Trasparent and Data Collection

**Comment by ptrbojko** [comment]
I will try to add new thing just for debug and protocol/codes discovery purposes. This, maybe, would help to tinker around your inverter - what codes does it support and data it returns.

**Comment by antcan66** [comment]
> I will try to add new thing just for debug and protocol/codes discovery purposes. This, maybe, would help to tinker around your inverter - what codes does it support and data it returns.

Okay. Thanks, I look forward to hearing from you

**Comment by ptrbojko** [comment]
Hi, here https://github.com/ptrbojko/openhab-lsw4inverter-binding/actions/runs/4852055852 you have first build with a debug thing. You setup this as any other things. However, two new config properties must be filled: startRegister and endRegister.

Basically you can try to use following values:
0x0400 and 0x042B
0x0404 and 0x0420
0x0400 and 0x0420

There is a channel called lastResponse that will be populated with an response from your logger/inverter.

**Comment by antcan66** [comment]
Thank 

> Hi, here https://github.com/ptrbojko/openhab-lsw4inverter-binding/actions/runs/4852055852 you have first build with a debug thing. You setup this as any other things. However, two new config properties must be filled: startRegister and endRegister.
> 
> Basically you can try to use following values: 0x0400 and 0x042B 0x0404 and 0x0420 0x0400 and 0x0420
> 
> There is a channel called lastResponse that will be populated with an response from your logger/inverter.

lastResponse A5:17:00:10:45:03:00:AE:02:

**Comment by ptrbojko** [comment]
For each of those 3 permutation?
0x0400 and 0x042B
0x0404 and 0x0420
0x0400 and 0x0420
