### ISSUE TITLE
Support for Deye 3 inverter

### ISSUE THREAD

**Issue by devtnrok** [ptrbojko/openhab-lsw4inverter-binding#6]
Thing is Online but all channels are "Null".

My serial number is 23xxxxxxxx FW is LSW3_15_FFFF_1.0.84

Inverter is Deye 3 phase 10K

Great work and brilliant if you can make this work! :D 

I already tried the Transparent Work mode - no change

**Comment by ptrbojko** [comment]
Deye is not supported yet. It has different modbus registers than current supported inverters.

**Comment by devtnrok** [comment]
Thanks for reply. Keep up the good work!👍

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ptrbojko** [comment]
There are some modbus registers noted on github for deye. Within #5 some debug thing will be created to tinker around checking whether they are valid for your inverter.

**Comment by ptrbojko** [comment]
I have created a debug thing to check whether assumed modbus codes works for appropriates inverters - see comment https://github.com/ptrbojko/openhab-lsw4inverter-binding/issues#issuecomment-1529792748.

You could tinker arround those definitions - https://github.com/StephanJoubert/home_assistant_solarman/tree/main/custom_components/solarman/inverter_definitions (see deye files) and check if registers mentioned there works for you. As working I mean that lastResponse channel produces somewhat long response (more than 14-20 bytes, like 100 or more).

**Comment by ptrbojko** [comment]
Stalled issue
